CREATE TABLE ACCOUNTS(
    Email VARCHAR(89) NOT NULL,
    UserName VARCHAR(50) NOT NULL,
    PasswordHash BINARY(60) NOT NULL,
    Path VARCHAR(260) DEFAULT 'default_icon.png',
    PRIMARY KEY(Email)
); CREATE TABLE POSTS(
    Title VARCHAR(100),
    Message TEXT,
    PostTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Author VARCHAR(89),
    PRIMARY KEY(Title)
);